# coding=utf-8
# pylint: disable=too-many-lines
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.8.4, generator: @autorest/python@6.0.1)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from typing import overload, Mapping, Any
from azure.core.serialization import Model, rest_field


class PostInput(Model):
    """PostInput

    All required parameters must be populated in order to send to Azure.
    """
    url: str = rest_field()

    @overload
    def __init__(self, *, url: str):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any], /):
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
